//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassKeeperEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passwords
    {
        public int PasswordID { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
